### ISSUE TITLE
不適用於香港蘋果日報嗎？

### ISSUE THREAD

**Issue by yujinlin0224** [chuck-lee/tw-apple-daily-news-revealer#20]
香港蘋果日報 https://hk.news.appledaily.com 好像沒有效

**Comment by JasonHK** [comment]
You can bypass Hong Kong Apple Daily paywall by simply inject a few lines of JavaScript:

```javascript
// Desktop Site Bypass
Object.defineProperty(window, "OMOSubscFlag", {
    writeable: false,
    value: false
});

// Mobile Site Bypass
Object.defineProperty(window, "OMOureadEnable", {
    writeable: false,
    value: false
});
```

**Comment by chuck-lee** [comment]
Thank you for your code snippet!

But the snippet doesn't work because firefox addon can only access `docuement` object, not `window` object.
