### ISSUE TITLE
不適用於運動版面的新聞

### ISSUE THREAD

**Issue by darkwindcf** [chuck-lee/tw-apple-daily-news-revealer#23]
感謝作者Chuck Lee分享這麼好用的extension
不過似乎不適用蘋果的體育版面，開頭為 
https://tw.sports.appledaily.com/sports/*
的頁面仍無法讀取，希望能加入列表
謝謝！

Your user

**Comment by chuck-lee** [comment]
不好意思沒收到有這個issue的通知。
只知道前一陣有一次改版，也許是那次改版的影響讓extension失效。
更新後的extension可以正常看體育版面，找到回報當天的體育新聞做測試（https://tw.sports.appledaily.com/sports/20191112/2IJ546M6QHU6CEUGI6JVNGGTLU/ ）也正常，所以視為解決了吧！
